services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: median-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - ./src/mail/assets:/app/dist/src/mail/assets 
    command: sh -c "npm install && npx prisma db push --skip-generate && npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/median-db"

volumes:
  postgres: