name: Deploy Azure

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      ################################
      # BUILD BACKEND
      ################################

      - name: Build Backend
        run: |
          docker build \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:${{ env.IMAGE_TAG }} \
            ./backend

      - name: Push Backend
        run: |
          docker push \
            ${{ secrets.ACR_NAME }}.azurecr.io/backend:${{ env.IMAGE_TAG }}

      ################################
      # BUILD FRONTEND
      ################################

      - name: Build Frontend
        run: |
          docker build \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:${{ env.IMAGE_TAG }} \
            ./frontend

      - name: Push Frontend
        run: |
          docker push \
            ${{ secrets.ACR_NAME }}.azurecr.io/frontend:${{ env.IMAGE_TAG }}

      ################################
      # TERRAFORM
      ################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve

      ################################
      # UPDATE ACA BACKEND
      ################################

      - name: Deploy Backend
        run: |
          az containerapp update \
            --name ${{ secrets.BACKEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/backend:${{ env.IMAGE_TAG }}

      ################################
      # UPDATE ACA FRONTEND
      ################################

      - name: Deploy Frontend
        run: |
          az containerapp update \
            --name ${{ secrets.FRONTEND_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/frontend:${{ env.IMAGE_TAG }}